### ISSUE TITLE
Component with dot in its name throws a 'Component is not defined' error

### ISSUE THREAD

**Issue by daganomri** [hashicorp/next-mdx-remote#115]
When trying to access a component that is with a dot in his name, a component is not defined is thrown.
I can circumvent this by redeclaring it to a new component name without a dot (motion.div > MotionDiv).

**Comment by jescalan** [comment]
Thanks for the report! IMO component names containing dots are generally not recommended overall, but it's good to know that there's a hard limitation with mdx remote. Would you be interested in adding this to the "caveats" section in the readme, as a pull request, since you found it? It would be a great way to get in an easy contribution 😀

**Comment by BRKalow** [comment]
This should now be possible as of `v3.0.0`, please see ["Additional Examples" in the README](https://github.com/hashicorp/next-mdx-remote#additional-examples).
