### ISSUE TITLE
How can you import/use data in MDX with this library?

### ISSUE THREAD

**Issue by podolsk-maxi** [hashicorp/next-mdx-remote#116]
I want to use the below standard MDX:

```
import snowfallData from './snowfall.json'
import BarChart from './charts/BarChart'

# Recent snowfall trends

2019 has been a particularly snowy year when compared to the last decade.

<BarChart data={snowfallData} />
```

How can I use this library and use a data source without importing it?
If I need to load data in the component itself, is it possible to use an API, or will that fail when hydrated?

**Comment by jescalan** [comment]
Imports are not possible with this library. Take a moment to read through the readme, which will give you instructions on how to use the library 😀

I'm going to close this since it's a support request and not an issue, but please feel free to follow up with any other questions you have after reading through the usage instructions!
