### ISSUE TITLE
Disable hydration in v3?

### ISSUE THREAD

**Issue by NateRadebaugh** [hashicorp/next-mdx-remote#133]
Can I improve performance by disabling hydration altogether? I'm effectively just using this for read-only non-interactive content and at least in some cases won't need to perform the hydration step. I don't think `lazy` is enough here.

**Comment by llldar** [comment]
Me too, I was using it to reduce client side bundle size and not really need hydration.

**Comment by BRKalow** [comment]
You _might_ be able to accomplish what you want with a pattern like this:

```jsx
const ServerOnlyMDXRemote = React.memo((props) => {
  // on the server, render as normal, pass lazy to ensure a wrapping div is rendered
  if (typeof window === 'undefined') return <MDXRemote {...props} lazy />

  // on the client, render an empty div which will force React to retain the SSR'd markup
  return <div dangerouslySetInnerHTML={{ __html: '' }} suppressHydrationWarning />

// Force the component NOT to re-render to preserve the markup
}, () => true);
```

Usage would be as usual:
```jsx
<ServerOnlyMDXRemote {...mdxSource} />
```

Bear in mind that due to the nature of how `getStaticProps` works, the result of `serialize` will be shipped to the client regardless of whether or not you hydrate.

The alternative would be to use an approach similar to what was used in v1/v2 and actually render the MDX in `getStaticProps` and only ship the markup, but past caveats such as lack of context support and shipping duplicative markup would apply again.

```jsx
async function getStaticProps() {

  // ...

  const mdxSource = await serialize(mdx)
  const markup = renderToStaticMarkup(<MDXRemote {...mdxSource} />)

  // ...

  return {
    props: { markup }
  }
}
```

**Comment by BRKalow** [comment]
I'm going to close this, as we don't plan to support this behavior out of the box. Feel free to re-open if things aren't working for you or you would like to continue the discussion. Thanks!

**Comment by max-pod** [comment]
@BRKalow Can you expand on what you mean by "the nature of how `getStaticProps` works, the result of serialize will be shipped to the client regardless of whether or not you hydrate." How? Shouldn't the rendered HTML be the only thing that's getting passed down?

I'm also getting confused by this comment: https://github.com/hashicorp/next-mdx-remote/issues/147#issuecomment-846430758: "shipping the markup **twice** (both in the serialized data as well as in the document HTML). I would definitely recommend using that approach instead of rolling back."

Get static props only return `markup`, so are you saying that the 'markup constant' that gets returned is really a function that hasn't been executed yet?
