### ISSUE TITLE
How to use layout like next-mdx-enhanced 

### ISSUE THREAD

**Issue by muke5hy** [hashicorp/next-mdx-remote#153]
I am trying to port my toy site to use next-MDX-remote, but it is not loading the correct template 

in MDX enhanced all MDX pages used load defined layout. 
```
---
layout: 'tutorial'
title: 'Bash'
---
```

How do I do the same with MDX remote, any example will help a lot.

**Comment by jescalan** [comment]
Hey @muke5hy - mdx-remote doesn't have any built-in frontmatter processing nor does it handle layouts in this way. It seems like maybe you are moving over from `next-mdx-enhanced`, but the two libraries are dramatically different. I'd recommend checking out the [examples in the readme](https://github.com/hashicorp/next-mdx-remote#examples) for more guidance here. The gist is that you don't define a separate file as the layout, you instead load your mdx into your layout file directly through `getStaticProps`.

I'm going to close this since it's not an issue and is more of a support request but please feel free to continue discussing here!
