### ISSUE TITLE
ReferenceError: title is not defined

### ISSUE THREAD

**Issue by rodbs** [hashicorp/next-mdx-remote#16]
I've tried out the second example , the one parsing the variable  `title ` with gray matter.
It raises this error:
![image](https://user-images.githubusercontent.com/4244067/87788881-6d917c00-c83e-11ea-9582-a87156b54afb.png)

It's not picking up `title `from front-matter

I've replicated the error in this repo (in  `testpage2.js`   )
https://github.com/rodbs/nextjs-mdx-remote

Btw, the mdx source has to be within template literals?  what about if I get it from a db? how a parse it?
```
  const source = `
---
title: Test
---

Some **mdx** text, with a component <Test name={title}/>
`
```

Thanks

**Comment by jescalan** [comment]
Hi again! So sorry about that, there was a typo in the readme. The third parameter to this function is for mdx options, and the fourth param is for scope data. Just adjusted the readme right now. I'm planning to break down this function's props to an object instead of individual params to make this more clear, but that is a massively breaking change so I haven't rushed it out the door.

To fix your example, change [this line](https://github.com/rodbs/nextjs-mdx-remote/blob/master/pages/testpage2.js#L28) to:

```js
const mdxSource = await renderToString(content, components, null, data);
```

**Comment by jescalan** [comment]
Thank you as well for filing such clear issue and digging up all these bugs! I'm so sorry you keep running into trouble, this library is in its early phases and I appreciate you putting it through the paces 😀

**Comment by rodbs** [comment]
Hi, @jescalan 

I've implemented your changes, and updated the package, but it keeps failing. Not sure if I'm doing something wrong.
https://github.com/rodbs/nextjs-mdx-remote

**Comment by jescalan** [comment]
Ah yes, you also put a newline before the front matter so `gray-matter` was not picking it up. On [this line](https://github.com/rodbs/nextjs-mdx-remote/blob/master/pages/testpage2.js#L20), you need to have the three dashes start there instead of below on a newline. So it should look like this:

```js
  const source = `---
title: Test
---
Some **mdx** text, with a component <Test name={title}/>
`;
```

**Comment by rodbs** [comment]
Thx, it works in the example. I have to test it in my project retrieving mdx from db
