### ISSUE TITLE
Prevent using unsafe evaluation

### ISSUE THREAD

**Issue by KarthikeyanRanasthala** [hashicorp/next-mdx-remote#19]
Using [`new Function(...)`](https://github.com/hashicorp/next-mdx-remote/blob/16f2d73021ff1356d66015cd6af2be0ad097b88d/hydrate.js#L43) is an unsafe evaluation and is strictly violating the practises for Content Security Policy as mentioned [here](https://developer.chrome.com/extensions/contentSecurityPolicy#relaxing-eval). This is a possible XSS attack vector.

This single line of code will raise a red flag for so many companies/people from using this package due to this security concern. I would request the contributors/maintainers to find an alternate way to accomplish the same and hopefully fix this in the upcoming releases with priority.

Apart from that, it's a really great project. 👍

**Comment by jescalan** [comment]
Hey @KarthikeyanRanasthala!

Just because a specific pattern _can_ be used in an unsafe manner doesn't mean it _always_ is. With functions that evaluate string to javascript code, the typical unsafe scenario is when user input or URLs are passed to such functions, which would allow an attacker to execute any javascript of their choosing on your website. Unless you decide to pass a url or user input through to the `hydrate` function, which would be a very unusual and ill-advised usage pattern, this is not a problem. In general, it's not really doing much to say that this is a "possible" XSS attack vector, better is to show that it _actually_ is an attack vector or point out a real security flaw in the library. Unless someone can come forward and point out an actual security flaw, there is not one.

That being said, I am also entirely open to suggestions for alternatives to the function constructor. A string of javascript must be evaluated in order for this to work, and the only other option I was aware of is `eval`, which is definitely worse. Compiling the mdx into a file and injecting an import kind of defeats the purpose of the library itself, which is to avoid reliance on the filesystem.

Regardless, I think this is something I should add a note about in the readme, and I will make sure to do so!

**Comment by jescalan** [comment]
Added a note about this - hopefully this does the trick!

https://github.com/hashicorp/next-mdx-remote/commit/00fdcd965ccc776352253e8c3ba5949604d4b03b
