### ISSUE TITLE
Had deployment failure with 3.0.6, fixed by installing 3.0.5

### ISSUE THREAD

**Issue by demonhunter3333** [hashicorp/next-mdx-remote#197]
Hi guys, just letting you know that 3.0.5 did not cause deployment failures for me as 3.0.6 did.

**Comment by jescalan** [comment]
What was the deployment failure?

**Comment by makyfj** [comment]
I had the same issue as well, my version was 3.0.4. I had to upgrade to 3.0.5. Then, it asked me to install @babel/core as a development dependency. It worked like a charm. Ty for the help.

**Comment by jescalan** [comment]
Ok, so this is a different issue then for you @hassanzadeh - the topic originally related to an issue caused by the `3.0.6` release, but it looks like it has never worked for you.

I have a number of projects that run perfectly well off `3.0.4` and `3.0.5` on vercel, so this seems likely to be something isolated to your use case. If there's anything we can do to help here, I think it would have to start with a minimal reproduction.
