### ISSUE TITLE
Plans to fetch data using co-location within JSX

### ISSUE THREAD

**Issue by noahlst** [hashicorp/next-mdx-remote#203]
The newly announced Next.js 12 signals a future shift by the Next team to move away from 'data functions' like `getStaticProps` to co-locating data collection within JSX.

~~Builds using experimental React 18 (which is in alpha) features - like SSR and RSC - on Next 12 currently fail.~~

Are there plans to adapt the `next-mdx-remote` package into this new model?

**Comment by gamedevsam** [comment]
I get errors with React 18: 

```
Module not found: Package path ./jsx-runtime.js is not exported from package /home/sbatista/Dev/Personal/sambatista.com/node_modules/react (see exports field in /home/sbatista/Dev/Personal/sambatista.com/node_modules/react/package.json)
```

**Comment by fernpolo** [comment]
Hi team! The original purpose of this issue was really based on two parts — hooks/colocating as raised at Next.js Conf 2021; and React SSR/Server Components. With React 18 now in GA and `4.0.1` capable of `<Suspense>`, SSR, etc  (#255, #250, #237, more), I've renamed this to focus on the latter only.

**Comment by fernpolo** [comment]
At this time, if you're experiencing errors with React 18 concurrency features, check:

- that `next-mdx-remote` is pinned at version `4.0.1`
- that you are using the latest version of Next.js (`12.1.4` at writing)
- that you're using the latest version of React (i.e. `18.0.0` proper)
- that your `next.config.js` includes `experimental: { runtime: "nodejs"}` (Edge Runtime disables `eval` which this library requires)

If none of that works try adding this to your `next.config.js`:

```js
webpack: (config) => {
    config.resolve.alias = {
      ...config.resolve.alias,
      "react/jsx-runtime.js": path.resolve("node_modules/react/jsx-runtime"),
    };
    return config;
  },
```

Or you can try `require.resolve` instead of `path`. This is courtesy of @jakejarvis 

Note that, with time, this will probably break!

**Comment by kwiat1990** [comment]
@fernpolo ich have also encountered that very problem, but in my case none of the above had worked and it produced the following error instead:

```
Error: Package subpath './jsx-runtime.js' is not defined by "exports" in /Users/mateusz.kwiatkowski/Playground/proste-opowiesci-nextjs/node_modules/react/package.json imported from /Users/mateusz.kwiatkowski/Playground/proste-opowiesci-nextjs/node_modules/next-mdx-remote/dist/index.js
```
Have you guys any ideas what's going on and how it can be fixed?

I'm looking for a solution to process a markdown content on the server, so that I can retrieve dimension of remote images and use it in with the Next `Image` component.

**Comment by BRKalow** [comment]
Closing this for now, thanks for raising the question! We'll be following the progress of the data-fetching evolutions in Next.js and look at how we'll be able to update `next-mdx-remote` to fit into the new patterns as more information comes out.
