### ISSUE TITLE
Problem with @gitgraph/react package

### ISSUE THREAD

**Issue by ali4heydari** [hashicorp/next-mdx-remote#204]
Hi,
Thanks for your great package ❤
I want to use the `Gitgraph` component from [`@gitgraph/react`](https://github.com/nicoespeon/gitgraph.js/tree/master/packages/gitgraph-react) package in my `.mdx` files but I get an error.
 I created a minimal [stackblitz](https://stackblitz.com/edit/nextjs-3mgcud) to show the problem. Please take a look.
Thanks!

**Comment by jescalan** [comment]
Hey, so I poked into this a little bit and found that it seems to be not an issue with gitgraph itself, since this renders fine with only the `master` code:

```
const master = gitgraph.branch("master");
master.commit("Initial commit");
```

It's once you add the develop merging to master that it chokes on the output. The error is quite clear - there are adjacent jsx tags that are not wrapped. This is something that would need to be remedied within gitgraph, as far as I can tell.
