### ISSUE TITLE
Anyone got styled-jsx working with next-mdx-remote?

### ISSUE THREAD

**Issue by homumado** [hashicorp/next-mdx-remote#208]
NextJS comes with [styled-jsx support](https://github.com/vercel/styled-jsx) by default, so it would be nice if we can use that with ```next-mdx-remote` as well.

Right now if I write into a MDX file,

```
<style jsx>{`
  p {
    color: red;
  }
`}</style>
```

Serializer would simply wrap this into a code block.

![image](https://user-images.githubusercontent.com/84349818/141534890-17d73492-9fe3-4f95-9992-b8e826baefcd.png)

What I expect (or hope it would do instead)

![image](https://user-images.githubusercontent.com/84349818/141534950-87905b7b-f78b-44fe-ad8f-b7e482482cd5.png)

**Comment by jescalan** [comment]
This is way beyond the scope of what this library would be able to provide. You may be able to run a remark plugin that would output the tags as html nodes rather than escaping them, I think that's the route I would take if you really want this to work. But depending on how the styled jsx support works for nextjs and at what phase it parses info, even this may do the trick.

Going to close this since it's not specifically an issue with this library, but I welcome anyone to continue discussion here if you want!
