### ISSUE TITLE
"Component X was not imported, exported, or provided by MDXProvider as global scope"

### ISSUE THREAD

**Issue by nxcco** [hashicorp/next-mdx-remote#220]
I implemented a dynamic importing of different components, depending on the blog post, written in mdx.

The code below shows the dynamic page and the dynamic importing.

```
const Post = ({ mdxSource, frontmatter }: PostProps): JSX.Element => {
  const [components, setComponents] = useState<Record<string, ReactNode>>()

  useMemo(async () => {
// Here we load the components dynamically.
    const loadedComponents = await import(
      "../../components/posts/" + frontmatter.id
    )

    setComponents(loadedComponents.default)
  }, [])

  return (
    <div>
      <MDXRemote
        {...mdxSource}
        components={components === undefined ? {} : components}
      />
    </div>
  )
}
```

I face this error message, even though everything works correctly.
What could be the reason?

**Comment by XanderJL** [comment]
They have this behavior documented in [their README](https://github.com/hashicorp/next-mdx-remote#caveats). A workaround is just adding your imports to the components prop in `<MDXRemote />`, but that's gross and makes this plugin pretty useless 🤷‍♂️ 

They mentioned they want to support this functionality in the future, but the last update in the issues was from August, so do with that info what you will.

**Comment by jescalan** [comment]
We have been thinking consistently about how it might be possible to add this functionality without massive drawbacks, and so far have come up short. It would sort of require implementing a small bundler or doing some deep integration with webpack in order to make this possible, since mdx-remote operates entirely outside of webpack by loading data though `getStaticProps` currently.

We very much welcome ideas and contribution along these lines! There is also `next-mdx-enhanced` available for use, though we do not maintain it anymore, it is tied in directly with webpack and can run import/exports, though as a consequence it's much slower and does not scale well.
