### ISSUE TITLE
MDXRemote & compileMDX from 'next-mdx-remote/rsc' types still require compiledSource

### ISSUE THREAD

**Issue by SanderCokart** [hashicorp/next-mdx-remote#336]
MDXRemote & compileMDX from 'next-mdx-remote/rsc' types still requires compiledSource

![image](https://user-images.githubusercontent.com/45256817/215486401-1794c7f7-aaaa-4fb4-be95-c9d24da8e01e.png)

**Comment by chrisweb** [comment]
Hmmm I searched for this bug in the tickets but didn't find it because I only searched in open tickets, like I usually do, then I cloned the repo and fixed it by myself, to then find out there is already a PR (which I didn't find at first either as it is closed too), it is just that the fix has not been released yet

@BRKalow I was wondering if a ticket should not stay open until it has been released to avoid cases like this?
