### ISSUE TITLE
Question: passing an extra prop to the wrapper component

### ISSUE THREAD

**Issue by gr-qft** [hashicorp/next-mdx-remote#45]
I'm using the function `renderToString` like this: 

```js
 const mdxSource = await renderToString(content, {
    components,
    mdxOptions: {
      remarkPlugins: [math],
    },
    scope: data
  });
```

`components` contains `wrapper` which allows me to style the layout (`wrapper: ({ children, ...props }) => {//...}`. Is it possible to pass a prop into my wrapper component so that I have access to it inside `wrapper`? I tried to follow the provider discussion 

https://github.com/hashicorp/next-mdx-remote/pull/35

but I'm not sure if that's what I'm looking for. 

By the way,  what is `scope` for and where is it accessible?

Thanks!

**Comment by jescalan** [comment]
If you're trying to bind a prop to the wrapper component, you'd need to wrap the wrapper I think 😂

So like,

```js
(function wrapperWithExtraProps(...props) {
  return wrapper(props)
})(mySpecialProp, otherProp)
```

With the `scope` argument, you can add an object and that object will be accessible via component props. So for example:

```js
const content = `# Some Page

<SomeComponent prop={foo} />
`
const mdxSource = await renderToString(content, { scope: { foo: 'bar' })
}
```

Hope this helps!

**Comment by gr-qft** [comment]
Thanks ! For `wrapperWithExtraProps` it seems `wrapper` inside it, which is used to parse mdx into a string, only get `children` as `props` still even though `mySpecialProp` and `otherProp` are passed to the outer function. But I could have misunderstood somewhere, I'll spend more time playing around with it later. 

For `scope`, I tried and it worked. So it's useful for passing data into components called inside mdx, but not for the **core components** (components such as h1, h3, etc., which are called "behind the scene").

**Comment by kamal-choudhary** [comment]
Hi, I have a use-case with wrapper inside components, that's why I am posting it here.

I am using the wrapper to access all the children of the MDX file and then filtering the headers.

I can filter the header elements using the code below. But I can't seem to store these filtered headers anywhere.

Like, I can't use the setState here because it is inside a Javascript function. 

Also, can't use a variable because if I use then it will be scoped only to this function.

`const components = {
  wrapper: ({ children, ...props }) => {
    filteredChildren = filterHeaderElements(children);
   // I want to store the value of this filteredChildren somewhere
    return <>{children}</>;
 },
  SomeOtherComponent,
};`

Any help would be much appreciated.

P.S: I'm not too sure whether I should post the question here. If I am wrong, then please do let me know. I'll delete it from here. Thank you.

**Comment by cleversprocket** [comment]
I think this issue was prematurely closed. Having to wrap the wrapper isn't a great solution. I'm using the following work around for now:

```typescript
import components from "./components";

const Post: NextPage = (props) => {
  const {serializedContent, ...rest} = props;
  const wrappedComponents = useMemo(() => {
    return {
      ...components,
      wrapper: (props) => <components.wrapper {...rest} {...props} />
    };
  }, [rest]);

  return (
    <MDXProvider components={wrappedComponents}>
     // I'm also passing components to MDXRemote because it's not taking them from MDXProvider for some reason.
      <MDXRemote components={wrappedComponents} scope={rest} {...serializedContent} />
    </MDXProvider>
  )
};
```

**Comment by maxlapshin** [comment]
This is nice, but it works only on client side. MDXProvider cannot be used on server side
