### ISSUE TITLE
Code blocks that contain import statements are picked up as attempts to literally import things

### ISSUE THREAD

**Issue by AleksandrHovhannisyan** [hashicorp/next-mdx-remote#51]
Hey! First off, thanks a bunch for this package! I was pretty excited to get it working :) The only issue is if I try to include code blocks that have import statements:

```
Support for the experimental syntax 'flow' isn't currently enabled (1:8):
```

I'm using prism-react-renderer, which supports import statements in code. It seems next-mdx-remote is reading those imports literally and expecting to import a package. My page rebuilds just fine if I get rid of the import statements.

Example (gibberish) code that triggers this:

```tsx
a;

b;
```

It seems the newline is the issue, for whatever reason 🤔 

Edit: This seems relevant: https://github.com/mdx-js/mdx/issues/218. I think it's an MDX/remark issue.

**Comment by jescalan** [comment]
Imports are not allowed at all using `next-mdx-remote`: https://github.com/hashicorp/next-mdx-remote#caveats

There is not really a way this can be resolved - I would recommend proposing a change to prism-react-renderer so that it does not inject imports, or using another syntax highlighting library. I'm sorry!

**Comment by AleksandrHovhannisyan** [comment]
All good!
