### ISSUE TITLE
How to go about managing post related assets like images, OG image etc

### ISSUE THREAD

**Issue by GorvGoyl** [hashicorp/next-mdx-remote#66]
I like the structure where post markdown and its assets are stored in same folder for easier management instead of creating post mdx files and then storing all posts assets in a different folder. So, is it possible to keep post and its assets in their respective folder and still access them when using this library?
For example:
```
project:
   /posts
     /my-first-post
        -index.mdx
        -first-post.png
        -og.png
    /my-second-post
        -index.mdx
        -second-post.png
        -og.png

```

**Comment by jescalan** [comment]
Keeping images outside the root `public` folder isn't going to work, since nextjs exposes anything inside the `public` folder as a public asset, but everything else is treated as internal. Otherwise you can organize folders however you want!

Going to close this since it's a question and not an issue, but please feel free to keep discussing if you want.

**Comment by tuliofaria** [comment]
@GorvGoyl I was able to accomplish this. Take a look into my answer on this: https://stackoverflow.com/questions/63957018/how-to-use-images-in-a-mdx-file-outside-of-public-folder-while-using-next/65681762#65681762

**Comment by jescalan** [comment]
Really fantastic and creative solution - +1 from me!
